### ISSUE TITLE
How to run e4-webui as shown on website ?

### ISSUE THREAD

**Issue by bhaveshgohel** [teserakt-io/c2#30]
Hello Team,
I'm having difficulty setting up the server as shown in the website main page [video](https://teserakt.io/video/e4-webui.mp4).

can you please help? :smiley:

I have followed bellow steps:
```bash
./script/build.sh
docker-compose up -d
./bin/c2
```

_P.S: If this is not the correct repo to report. please guide. Thank you. :pray:_

**Comment by veorq** [comment]
Hi! Could you please elaborate on your problem or error messages?

**Comment by daeMOn63** [comment]
Hello, if you're looking for the webui, you can find it over https://github.com/teserakt-io/webui, we just made it public :)

**Comment by bhaveshgohel** [comment]
Hello @daeMOn63 Thank you. :pray: 
This is what exactly i was looking for the. :+1:
